import type { VercelRequest, VercelResponse } from '@vercel/node';
import { sql } from '@vercel/postgres';

export default async function handler(request: VercelRequest, response: VercelResponse) {
  try {
    // 1. Create visitor_logs table
    // We use BIGINT for timestamps to match the Date.now() format used in the app
    // We use TEXT for visitor_id to handle the string IDs generated by the frontend
    await sql`
      CREATE TABLE IF NOT EXISTS visitor_logs (
        id SERIAL PRIMARY KEY,
        visitor_id TEXT NOT NULL,
        name TEXT,
        department TEXT,
        organization TEXT,
        laptop_name TEXT,
        laptop_color TEXT,
        serial_number TEXT,
        visitor_type TEXT,
        event_id TEXT,
        event_name TEXT,
        check_in BIGINT,
        check_out BIGINT,
        duration TEXT,
        status TEXT,
        custom_data JSONB,
        context TEXT
      );
    `;

    // 2. Create events table
    await sql`
      CREATE TABLE IF NOT EXISTS events (
        id SERIAL PRIMARY KEY,
        name TEXT,
        created_at BIGINT,
        custom_fields JSONB
      );
    `;

    return response.status(200).json({ 
        success: true, 
        message: "Database tables created successfully. You can now use the app." 
    });
  } catch (error) {
    console.error('Setup failed:', error);
    return response.status(500).json({ 
        success: false, 
        error: error instanceof Error ? error.message : String(error) 
    });
  }
}